"""specified string lengths for MySQL

Revision ID: fb9fc6db1f0a
Revises: 
Create Date: 2019-08-15 11:03:17.665065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9fc6db1f0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('secret_key', sa.String(length=120), nullable=True),
    sa.Column('desc', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('feed_moment',
    sa.Column('feeder_id', sa.Integer(), nullable=True),
    sa.Column('feedmoment_id', sa.Integer(), nullable=False),
    sa.Column('feed_time', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeder.id'], ),
    sa.PrimaryKeyConstraint('feedmoment_id')
    )
    op.create_table('feederusers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feeder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feeder_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feederusers')
    op.drop_table('feed_moment')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('feeder')
    # ### end Alembic commands ###
